# Tensorflow syntax basics

In [18]:
import tensorflow as tf

print(tf.__version__)

1.14.0


In [19]:
message = tf.constant("Hello")

type(message)

tensorflow.python.framework.ops.Tensor

In [20]:
# with tf.Session() as sess: (Old syntax)
with tf.compat.v1.Session() as sess:
    result = sess.run(message)

result

# b means bytes literal

b'Hello'

In [21]:
a = tf.constant(10)
b = tf.constant(20)

In [22]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [23]:
a + b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [24]:
with tf.compat.v1.Session() as sess:
    result = sess.run(a + b)

print(result)

30


In [25]:
num_const = tf.constant(10)

fill_matrix = tf.fill((4, 4), 10)

zeros = tf.zeros((4, 4))

ones = tf.ones((4, 4))

rand_nor = tf.random_normal((4, 4), mean=0, stddev=1.0)

rand_uni = tf.random_uniform((4, 4), minval=0, maxval=1)

operations = [num_const, fill_matrix, zeros, ones, rand_nor, rand_uni]

# only works with Jupyter notebook
sess = tf.InteractiveSession()

for op in operations:
    print(sess.run(op))
    print('\n')

# for op in operations:
#     print(op.eval())
#     print('\n')

sess.close()

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.16538543  0.53596294 -1.2627692  -2.4970055 ]
 [-0.2690669   0.61593264  0.2710623   0.4029504 ]
 [-0.21537758 -0.5924639   0.7779131  -1.8915228 ]
 [ 0.9896323  -1.3338048   1.1479089  -0.4059097 ]]


[[0.02032733 0.4636463  0.10303307 0.9051602 ]
 [0.9459379  0.88096833 0.87060773 0.4547013 ]
 [0.70774317 0.87511635 0.5722861  0.10245442]
 [0.9564127  0.9828001  0.80818725 0.51771903]]




In [35]:
a = tf.constant([
    [2, 2],
    [2, 2]
])

print("a: ", a.get_shape())

b = tf.constant([
    [2], [2]
])

print("b: ", b.get_shape())

result = tf.matmul(a, b)

with tf.compat.v1.Session() as sess:
    print(sess.run(result))

a:  (2, 2)
b:  (2, 1)
[[8]
 [8]]


NameError: name 'InteractiveSession' is not defined

## Tensorflow Graphs

In [27]:
# When we start the tensorflow, a default graph is created
graph_one = tf.get_default_graph()
print(graph_one)

In [28]:
# Create additional graph
graph_two = tf.Graph()
print(graph_two)

# Set graph_two as default
with graph_two.as_default():
    print(graph_two is tf.get_default_graph())

True


In [29]:
# Outside session still graph_one is the default graph
print(graph_two is tf.get_default_graph())

False


## Tensorflow variables and placeholders

There are 2 main types of tensor object in a graph:

1. Variables
    
   * During the optimization process, TF tunes the parameters of the model in our to fit the training data.
   * Variables can hold the values of weights and biases throughout the session.
   * Variables do need to be initialized.
    
2. Placeholders

   * Initially empty and are used to feed in the actually training examples.
   * They do need a declared expected data type (eg tf.float32) with an optional shape argument.

In [51]:
# Tensor flow Variables
import tensorflow as tf

sess = tf.InteractiveSession()

my_tensor = tf.random_uniform((4,4), 0, 1)
print(my_tensor)

# Create Tensor variable
my_var = tf.Variable(initial_value=my_tensor)
print(my_var)

# Variable need to initialize first before running else will throw error
# sess.run(my_var) # Throw FailedPreconditionError

# Initialize the variable
init = tf.global_variables_initializer()
sess.run(init)

# Run the variable
print(sess.run(my_var))

# Create Placeholder
ph = tf.placeholder(tf.float32)
print(ph)

sess.close()

Tensor("random_uniform_23:0", shape=(4, 4), dtype=float32)
<tf.Variable 'Variable_18:0' shape=(4, 4) dtype=float32_ref>
[[0.46670616 0.82471764 0.5722128  0.61715317]
 [0.9282005  0.58632135 0.32659602 0.22519696]
 [0.5983077  0.6121117  0.23408592 0.37509763]
 [0.5936545  0.02030551 0.5417532  0.38893032]]
Tensor("Placeholder_3:0", dtype=float32)
