# Linear Algebra

Notes:

* Math wise performing any matrix operation for different shape is not allow or does not make sense. But in programming (Python), a scalar can be operation to a vector even they are of different shapes. This is an exception and the operation will happen element wise.

In [4]:
import numpy as np

## Scalars

Scalars are `1 * 1` size

In [29]:
s = 5
print(s)
print(type(s))

# Below will throw error, as scalar is a 0-dimensional object. Thus, no-shape and no-transpose
# print(s.shape)
# print(s.T)

5
<class 'int'>


## Vectors

Vectors are of `m * 1` size

In [25]:
v = np.array([5, -2, 4]) # Default is row vector
print(v)
print(type(v))
print(v.shape)
print(v.T)

[ 5 -2  4]
<class 'numpy.ndarray'>
(3,)
[ 5 -2  4]


## Matrices

Matrices are of `m * n` size

In [26]:
m = np.array([
    [5, -2, 4],
    [-3, 0, 14]
])
print(m)
print(type(m))
print(m.shape)
print(m.T)

[[ 5 -2  4]
 [-3  0 14]]
<class 'numpy.ndarray'>
(2, 3)
[[ 5 -3]
 [-2  0]
 [ 4 14]]


## Tensors

Tensor are of `k * m * n` size

In [27]:
m1 = np.array([
    [5, -2, 4],
    [-3, 6, 2]
])

print(m1)

m2 = np.array([
    [-8, 7, 9],
    [1, -5, 3]
])
print(m2)

t = np.array([m1, m2])
print(t)
print(type(t))
print(t.shape)
print(t.T)

[[ 5 -2  4]
 [-3  6  2]]
[[-8  7  9]
 [ 1 -5  3]]
[[[ 5 -2  4]
  [-3  6  2]]

 [[-8  7  9]
  [ 1 -5  3]]]
<class 'numpy.ndarray'>
(2, 2, 3)
[[[ 5 -8]
  [-3  1]]

 [[-2  7]
  [ 6 -5]]

 [[ 4  9]
  [ 2  3]]]


## Inner product / Dot product / scalar product

Dot product means the sum of the products of the corresponding elements.

Below is allowed:
* `m*n` and `m*n`
* `m*n` and `n*m`

In [30]:
x = np.array([2, 8, -4])
y = np.array([1, -7, 3])
np.dot(x, y)

-66

In [40]:
x = np.array([
    [5, 12, 6, 4, 7],
    [-3, 0, 14, 7, 2],
    [9, 7, 4, 3, 6],
    [-4, 3, 6, 2, 9]
])
print(x.shape)

y = np.array([
    [2, -1],
    [8, 0],
    [3, 0],
    [4, 5],
    [6, 3]
])
print(y.shape)

result = np.dot(x, y)
print(result)
print(result.shape)

(4, 5)
(5, 2)
[[182  36]
 [ 76  44]
 [134  24]
 [ 96  41]]
(4, 2)
