# TensorFlow basics syntax

In [12]:
import tensorflow as tf

print(tf.__version__)

1.15.0-dev20190718


In [19]:
message = tf.constant("Hello")

type(message)

tensorflow.python.framework.ops.Tensor

In [20]:
# with tf.Session() as sess: (Old syntax)
with tf.compat.v1.Session() as sess:
    result = sess.run(message)

result

# b means bytes literal

b'Hello'

In [22]:
a = tf.constant(10)
b = tf.constant(20)

In [23]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [24]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [25]:
with tf.compat.v1.Session() as sess:
    result = sess.run(a + b)

print(result)

30


In [37]:
num_const = tf.constant(10)

fill_matrix = tf.fill((4, 4), 10)

zeros = tf.zeros((4, 4))

ones = tf.ones((4, 4))

rand_nor = tf.random_normal((4, 4), mean=0, stddev=1.0)

rand_uni = tf.random_uniform((4, 4), minval=0, maxval=1)

operations = [num_const, fill_matrix, zeros, ones, rand_nor, rand_uni]

# only works with Jupyter notebook
sess = tf.InteractiveSession()

for op in operations:
    print(sess.run(op))
    print('\n')

# for op in operations:
#     print(op.eval())
#     print('\n')

sess.close()

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.1505312  -0.17575602 -1.6852697   0.10362425]
 [-1.5839994  -0.5604833  -0.2462411   0.93608123]
 [ 2.7431006  -0.15747434 -0.21341136 -0.14698434]
 [-0.9650886   0.67266417  2.942394   -0.2091525 ]]


[[0.02560794 0.96614754 0.64473116 0.09973896]
 [0.8053353  0.28498566 0.79149854 0.87327003]
 [0.94782066 0.86811864 0.9237331  0.83718526]
 [0.00757194 0.78205585 0.3297671  0.9147426 ]]




In [43]:
a = tf.constant([
    [1, 2],
    [3, 4]
])

print("a: ", a.get_shape())

b = tf.constant([
    [10], [100]
])

print("b: ", b.get_shape())

result = tf.matmul(a, b)

with tf.compat.v1.Session() as sess:
    print(sess.run(result)

a:  (2, 2)
b:  (2, 1)
